version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: hahn
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: .
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"

volumes:
  postgres-data:
