spring:
  profiles:
    active: local

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 786828051327-6e0lp3f0rfl1d5r2tqbl2k2t3auhlg6c.apps.googleusercontent.com
            client-secret: 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

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

cloudinary:
  cloud_name: dsgnuek6y
  api_key: 194754251381395
  api_secret: IjBiLpzVcsT32bgCp-GBQjrZA-I
